server:
  port:
    5002

grpc:
  client:
    user-server:
      address: "static://localhost:9090"
      negotiationType: "plaintext"

jwt:
  refresh-time: 86400000
  access-time: 900000
  secret-key: "daksdkjafhjfoakwjihebsinokdwjeshigjeakeqpwjoensirjmkwjnisrf"
  header: "Authorization"
  prefix: "Bearer "

spring:
  data:
    redis:
      host: localhost
      port: 6379