server:
  port:
    ${SERVER_PORT}

grpc:
  client:
    user-server:
      address: ${GRPC_USER_SERVER_ADDRESS}
      negotiationType: "plaintext"

jwt:
  refresh-time: ${REFRESH_TIME}
  access-time: ${ACCESS_TIME}

oauth:
  google:
    client_id : ${GOOGLE_CLIENT_ID}
    client_pw : ${GOOGLE_CLIENT_PW}
    redirect_url : ${GOOGLE_REDIRECT_URL}

spring:
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}