server:
  port:
    ${SERVER_PORT}

grpc:
  server:
    address: ${GRPC_SERVER_ADDRESS}
    port: ${GRPC_SERVER_PORT}

  client:
    user-server:
      address: ${GRPC_USER_SERVER_ADDRESS}
      negotiationType: "plaintext"


jwt:
  refresh-time: ${REFRESH_TIME}
  access-time: ${ACCESS_TIME}
  header : "Authorization"
  prefix : "Bearer "

spring:
  data:
    redis:
      host: localhost
      port: ${REDIS_PORT}

mail:
  host: smtp.gmail.com
  port: 587
  username: ${MAIL_USERNAME}
  password: ${MAIL_PASSWORD}
  smtp:
    auth: true
    timeout: 5000
    starttls:
      enable: true
logging:
  level:
    root: trace
